// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWMQZSTqKB7mxNDxu2QqWulKCU0R3bkEU',
    appId: '1:426487682081:web:fb8afc96e1cd6d4b177f60',
    messagingSenderId: '426487682081',
    projectId: 'push-notification-c955f',
    authDomain: 'push-notification-c955f.firebaseapp.com',
    storageBucket: 'push-notification-c955f.firebasestorage.app',
    measurementId: 'G-DKN1T02GC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATc7A_DI6Hl77EZruOkFAuJcXIjtuVpqA',
    appId: '1:426487682081:android:32b161d3e5d6aba4177f60',
    messagingSenderId: '426487682081',
    projectId: 'push-notification-c955f',
    storageBucket: 'push-notification-c955f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7jMbwtSwHwD_YrvLgfQRSx058k5RAOK8',
    appId: '1:426487682081:ios:44af4427fbf606a0177f60',
    messagingSenderId: '426487682081',
    projectId: 'push-notification-c955f',
    storageBucket: 'push-notification-c955f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7jMbwtSwHwD_YrvLgfQRSx058k5RAOK8',
    appId: '1:426487682081:ios:44af4427fbf606a0177f60',
    messagingSenderId: '426487682081',
    projectId: 'push-notification-c955f',
    storageBucket: 'push-notification-c955f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWMQZSTqKB7mxNDxu2QqWulKCU0R3bkEU',
    appId: '1:426487682081:web:4841ca6760f19982177f60',
    messagingSenderId: '426487682081',
    projectId: 'push-notification-c955f',
    authDomain: 'push-notification-c955f.firebaseapp.com',
    storageBucket: 'push-notification-c955f.firebasestorage.app',
    measurementId: 'G-VKLQSDWS2T',
  );

}